<?php
namespace App\Command;

use App\GmailApi\Authentication\OauthAuthentication;
use App\GmailApi\Mailer\GmailHandler;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputOption;


class SimpleGmailCommand extends Command

{
    private $gmailService;

    public function __construct(GmailHandler $gmailService)
    {
        $this->gmailService=$gmailService;
        $this->emailConf=["sender"=>"","to"=>"","subject"=>"","body"=>""];

        parent::__construct();
    }

    protected function configure()
    {
        $this->setName("simplegmail")
            ->setDescription("Simple command to send email via Gmail API")
            ->setHelp("Help Message");
        $this
            ->addOption("sender",null,InputOption::VALUE_REQUIRED,"Sender's email")
            ->addOption("to",null,InputOption::VALUE_REQUIRED,"recipient's email")
            ->addOption("subject",null,InputOption::VALUE_REQUIRED,"email subject")
            ->addOption("body",null,InputOption::VALUE_REQUIRED,"email body");
        parent::configure(); // TODO: Change the autogenerated stub
    }
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        foreach ($this->emailConf as $k=>$v){
            $this->emailConf[$k]=$input->getOption($k);
            $output->writeln("$k:".$this->emailConf[$k]);
        }
        $client= (new OauthAuthentication())->createClient();
        $this->gmailService->createService($client);
        $message=$this->gmailService->createMail(
            $this->emailConf["sender"],
            array($this->emailConf["to"]),
            $this->emailConf["subject"],
            $this->emailConf["body"]
        );
        $this->gmailService->sendMail($message);

    }
}