<?php
namespace App\Command;

use App\GmailApi\Mailer\GmailHandler;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class SimpleGmailCommand extends Command

{
    public function __construct(GmailHandler $gmailService)
    {
        $this->$gmailService=$gmailService;
        $this->emailConf=["sender"=>"","to"=>"","subject"=>"","body"=>""];


        parent::__construct();
    }

    protected function configure()
    {
        $this->setName("simplegmail")
            ->addDescription("Simple command to send email via Gmail API")
            ->setHelp("Help Message");
        $this
            ->addArgument("sender",InputArgument::REQUIRED,"Sender's email")
            ->addArgument("to",InputArgument::REQUIRED,"recipient's email")
            ->addArgument("subject",InputArgument::REQUIRED,"email subject")
            ->addArgument("body",InputArgument::REQUIRED,"email body");
        parent::configure(); // TODO: Change the autogenerated stub
    }
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        foreach ($this->emailConf as $k=>$v){
            $this->emailConf[$k]=$input->getArgument($k);
            echo $v."\n";
        }
        parent::execute($input, $output); // TODO: Change the autogenerated stub
    }
}